// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

declare global {
    interface Window {
        __TAURI_INVOKE__<T>(cmd: string, args?: Record<string, unknown>): Promise<T>;
    }
}

const invoke = window.__TAURI_INVOKE__;

export function errorPopup(msg: string) {
    return invoke<null>("error_popup", { msg })
}

export function hide() {
    return invoke<null>("hide")
}

export function newGroup(group: Group) {
    return invoke<Group[]>("new_group", { group })
}

export function getGroups() {
    return invoke<Group[]>("get_groups")
}

export function updateGroup(group: Group) {
    return invoke<Group[]>("update_group", { group })
}

export function deleteGroup(index: number) {
    return invoke<Group[]>("delete_group", { index })
}

export type Group = { title: string; description: string; enabled: boolean; id: string; cron: string }
